#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_A, KC_B, KC_C, KC_D)
};

const uint16_t PROGMEM test_combo[] = {KC_A, KC_B, KC_C, KC_D, COMBO_END};
combo_t key_combos[COMBO_COUNT] = {COMBO_ACTION(test_combo)};

void process_combo_event(uint16_t combo_index, bool pressed) {
	backlight_step();
}
